name: all-in-one
on: 
  watch:
  issues:
    types: [labeled]
jobs:
  notify:
    name: notify-on-issue
    runs-on: ubuntu-latest
    steps:
      - name: echo-all
        run: |
          echo "${{toJson(github)}}"
          
