name: testing newcommers

on:
  issues:
    types: [opened, edited]

jobs:
  console:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo "${{github.sender}}"
          echo "${{github.actor}}"
          echo "${{github.event}}"
          echo "${{github.event.issue.html_url}}"
          echo "${{github.event.issue.labels}}"
          echo "${{github.event.issue.number}}"
          echo "https://github.com/${{github.repository}}"
