name: testing newcommers

on:
  issues:
    types: [opened, edited]

jobs:
  console:
    if: ${{ github.event.label.name }} == 'bug'
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo "${{github.sender}}"
          echo "${{github.actor}}"
          echo "${{github.event}}"
          echo "${{github.event.issue.html_url}}"
          echo "l=${{github.event.issue.labels}}" >> $GITHUB_ENV
          echo "${{github.event.issue.labels}}"
          echo "${{github.event.issue.number}}"
          echo "https://github.com/${{github.repository}}"
          echo "${{env.l}}"
          echo "${{github.event.labels.name}}"
          echo "${{github.event.labels}}"
  always-printing:
    runs-on: ubuntu-latest
    steps:
      - name: always-printing
        run: |
          echo "okokok"
