name: testing newcommers

on:
  label:
    types: [created]

jobs:
  console:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo "${{github.sender}}"
          echo "${{github.actor}}"
          echo "${{github.issue_number}}"
          