name: testing newcommers

on:
  issues:
    types: [opened, edited]

jobs:
  console:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo "${{github.sender}}"
          echo "${{github.actor}}"
          echo "${{github}}"

