name: testing newcommers

on:
  issues:
    types: [opened, edited]

jobs:
  console:
    runs-on: ubuntu-latest
    steps:
      - name: print
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_CONTEXT1: ${{ toJson(github.event) }} 
        run: |
          echo "${{github.sender}}"
          echo "${{github.actor}}"
          echo "${{github.event}}"
          echo "${{github.event.issue_number}}"
          echo "${{github.event.issue.number}}"
          echo "${{GITHUB_CONTEXT}}"
          echo "${{GITHUB_CONTEXT1}}"

