name: testing newcommers

on:
  issues:
    types: [opened, labeled]

jobs:
  good-first-issue-job:
    if: github.event.label.name == 'good first issue'
    name:  good-first-issue
    runs-on: ubuntu-latest
    steps:
      - name: always-printing
        run: |
          echo "${{github.sender}}"
          echo "${{github.actor}}"
          echo "${{github.event}}"
          echo "${{github.event.issue.html_url}}"
          echo "l=${{github.event.issue.labels}}" >> $GITHUB_ENV
          echo "${{github.event.issue.labels.*.name}}"
          echo "${{github.event.issue.number}}"
          echo "https://github.com/${{github.repository}}"
          echo "${{env.l}}"
          echo github.event.label.name
          echo github.event.label
