name: test-1
on:
  push: 
    branches: [master]
jobs:
  print-repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print repo name
        run : |
          echo "Hello $GITHUB_REPOSITORY"
          echo "hello ${{ github.repository }}"
          echo "repo_name=$GITHUB_REPOSITORY" >> $GITHUB_ENV
          echo "${{env.repo_name}}"
